# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    resources="$(az resource list --resource-group $(RESOURCEGROUPNAME) | grep id | awk -F \" '{print $4}')"
    for id in $resources; do
        az resource delete --resource-group $(RESOURCEGROUPNAME) --ids "$id" --verbose
    done
  displayName: 'Destroy infrastructure'
