# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

pool:
  name: Default


jobs:
  - job: Deploy_Infrastructure
    steps:
    - script: az account list  --all
      displayName: 'az account list'
    
    - script: |
        if [ $(az group exists --name $(RESOURCEGROUPNAME)) = false ]; then
            az group create \
              --name NadavHomework \
              --location "Central US"
        fi
      displayName: 'Check Resource Group Existence'

