# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default


jobs:
  - job: Deploy_Infrastructure
    steps:
    - script: echo
      displayName: 'echo arm deployment'
    - task: AzureCLI@2
      inputs:
        scriptType: bash
        azureSubscription: "MSEC_Candidates_Homeworks_new" 
        scriptLocation: 'inlineScript'
        inlineScript: 'az group list'