# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

pool:
  name: Default


jobs:
  - job: Deploy_Infrastructure
    steps:
    - script: az account list  --all
      displayName: 'az account list'
    
    - script: |
        if [ $(az group exists --name $(RESOURCEGROUPNAME)) = false ]; then
            echo "Crreating Resource Group."
            az group create \
              --name $(RESOURCEGROUPNAME) \
              --location "Central US"
        else
          echo "Resource Group Exists."
        fi
      displayName: 'Check Resource Group Existence'

    - script: |
        echo "Testing..."
      displayName: 'Test ARM Template'

    - script: |
        cd armTemplatets
        az deployment group create \
        --name DeployInfrastructure \
        --resource-group $(RESOURCEGROUPNAME) \
        --template-file main.json \
        --parameters parameters.json   \
        --parameters adminPublicKey="$(ADMINPUBLICKEY)"
      displayName: 'Deploy Resource from ARM Templates'

    





