# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

pool:
  name: Default

steps:

- task: SSH@0
  inputs:
    sshEndpoint: 'DeploymentServer'
    runOptions: 'inline'
    inline: |
      python -v
      git clone https://github.com/nadavSalman/azure-storage-accounts.git
      cd azure-storage-accounts/blobStorageClient && cat provision-blobs.sh
    readyTimeout: '20000'