# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    export ACCOUNT_A=`az storage account list --resource-group NadavHomework --query '[*].name' | yq .[0]`
    export ACCOUNT_B=`az storage account list --resource-group NadavHomework --query '[*].name' | yq .[1]`
    export KEY_ACCOUNT_A=`az storage account keys list --account-name $ACCOUNT_A  | yq .[0].value`
    export KEY_ACCOUNT_B=`az storage account keys list --account-name $ACCOUNT_B  | yq .[0].value`
  displayName: 'Extract Astorage Account Metadata & Credentials'

- script: |
    echo "Account A: $ACCOUNT_A"
    echo "Account B: $ACCOUNT_B"
  displayName: 'List accounts names'


- task: SSH@0
  inputs:
    sshEndpoint: 'DeploymentServer'
    runOptions: 'inline'
    inline: 'uname -a'
    readyTimeout: '20000'
