# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: SSH@0
  inputs:
    sshEndpoint: 'DeploymentServer'
    runOptions: 'inline'
    inline: 'python3 -V'
    readyTimeout: '20000'
  displayName: 'python3 version'



- task: SSH@0
  inputs:
    sshEndpoint: 'DeploymentServer'
    runOptions: 'git clone https://github.com/nadavSalman/azure-storage-accounts.git'
    inline: 'clone '
    readyTimeout: '20000'
  displayName: 'Clone nadavSalman/azure-storage-accounts'



- task: SSH@0
  inputs:
    sshEndpoint: 'DeploymentServer'
    runOptions: 'cd azure-storage-accounts/blobStorageClient && cat provision-blobs.sh'
    inline: 'clone '
    readyTimeout: '20000'
  displayName: 'Clone nadavSalman/azure-storage-accounts'